import UniformRandomMALA.Concrete.EuclideanTarget

/-!
# Elementary reductions for Bakry--Ledoux

This file records the part of the Bakry--Ledoux argument that is independent
of either localization or diffusion-semigroup infrastructure.  A potential
which is `m`-strongly convex is a convex perturbation of the quadratic
Gaussian potential `m * ‖x‖² / 2`.  We formulate convexity by its first-order
supporting-hyperplane inequality, since this is exactly the form supplied by
`FirstOrderPotential.lowerTaylor` and requires no Hessian API.

The resulting certificate is the common entrance point for both candidate
proofs:

* Bobkov localization applies to a log-concave density relative to a Gaussian;
* the semigroup route uses the same decomposition through the curvature lower
  bound in its Bochner estimate.
-/

namespace UniformRandomMALA

open MeasureTheory

noncomputable section

namespace Concrete
namespace FirstOrderPotential

variable {d : ℕ} (V : FirstOrderPotential d)

/-- A first-order certificate that `W` is convex with the displayed
subgradient `g`.  This deliberately avoids committing the Bakry--Ledoux proof
to Mathlib's differentiability-based convexity interface. -/
def FirstOrderConvexCertificate
    (W : State d → ℝ) (g : State d → State d) : Prop :=
  ∀ x y, W x + @inner ℝ (State d) _ (g x) (y - x) ≤ W y

/-- The part of `U` left after removing the quadratic Gaussian potential. -/
def gaussianResidual (x : State d) : ℝ :=
  V.U x - (V.m / 2) * ‖x‖ ^ 2

/-- The corresponding first-order residual field. -/
def gaussianResidualGrad (x : State d) : State d :=
  V.gradU x - V.m • x

/-- Squared contraction factor of one deterministic Euler drift step. -/
def eulerContractionFactorSq (h : ℝ) : ℝ :=
  1 - 2 * V.m * h + V.L ^ 2 * h ^ 2

/-- Contraction factor of one deterministic Euler drift step. -/
def eulerContractionFactor (h : ℝ) : ℝ :=
  Real.sqrt (V.eulerContractionFactorSq h)

/-- The squared Euler contraction factor is nonnegative for every real step
size.  This is an algebraic consequence of `0 < m ≤ L`; no small-step
assumption is required. -/
lemma eulerContractionFactorSq_nonneg (h : ℝ) :
    0 ≤ V.eulerContractionFactorSq h := by
  have hratio0 : 0 ≤ V.m / V.L := div_nonneg V.hm.le V.hL.le
  have hratio1 : V.m / V.L ≤ 1 := (div_le_one V.hL).2 V.hmL
  have hfirst : 0 ≤ 1 - (V.m / V.L) ^ 2 := by
    nlinarith
  have hid :
      V.eulerContractionFactorSq h =
        (1 - (V.m / V.L) ^ 2) + (V.L * h - V.m / V.L) ^ 2 := by
    unfold eulerContractionFactorSq
    field_simp [V.hL.ne']
    ring
  rw [hid]
  positivity

lemma eulerContractionFactor_nonneg (h : ℝ) :
    0 ≤ V.eulerContractionFactor h :=
  Real.sqrt_nonneg _

lemma eulerContractionFactor_sq (h : ℝ) :
    V.eulerContractionFactor h ^ 2 = V.eulerContractionFactorSq h := by
  exact Real.sq_sqrt (V.eulerContractionFactorSq_nonneg h)

/-- The Boltzmann weight is a standard quadratic Gaussian factor times the
log-concave perturbation generated by the residual potential. -/
lemma boltzmannWeight_eq_gaussian_mul_residual (x : State d) :
    V.boltzmannWeight x =
      Real.exp (-(V.m / 2) * ‖x‖ ^ 2) *
        Real.exp (-V.gaussianResidual x) := by
  rw [boltzmannWeight, ← Real.exp_add]
  congr 1
  simp only [gaussianResidual]
  ring

/-- Strong convexity, in the form already present in `FirstOrderPotential`,
says exactly that the Gaussian residual has supporting hyperplanes. -/
lemma gaussianResidual_firstOrderConvex :
    FirstOrderConvexCertificate V.gaussianResidual V.gaussianResidualGrad := by
  intro x y
  have htaylor := V.lowerTaylor x y
  have hnorm := norm_add_sq_real x (y - x)
  have hxy : x + (y - x) = y := by abel
  rw [hxy] at hnorm
  have hquad :
      -(V.m / 2) * ‖x‖ ^ 2 - V.m * @inner ℝ (State d) _ x (y - x) =
        -(V.m / 2) * ‖y‖ ^ 2 + (V.m / 2) * ‖y - x‖ ^ 2 := by
    rw [hnorm]
    ring
  simp only [gaussianResidual, gaussianResidualGrad, inner_sub_left,
    real_inner_smul_left]
  linarith

/-- The lower Taylor inequalities in the two directions imply strong
monotonicity of the recorded gradient. -/
lemma gradU_strongMonotone (x y : State d) :
    V.m * ‖x - y‖ ^ 2 ≤
      @inner ℝ (State d) _ (V.gradU x - V.gradU y) (x - y) := by
  have hxy := V.lowerTaylor x y
  have hyx := V.lowerTaylor y x
  have hsub : y - x = -(x - y) := by module
  rw [hsub, inner_neg_right, norm_neg] at hxy
  have hsum := add_le_add hxy hyx
  simp only [inner_sub_left]
  linarith

/-- One deterministic Euler drift step has the sharp small-step contraction
factor needed by the discrete Gaussian-image route.  In particular the loss
in the resulting Gaussian Lipschitz constant vanishes as `h → 0`. -/
lemma eulerDrift_sq_le (h : ℝ) (hh : 0 ≤ h) (x y : State d) :
    ‖(x - h • V.gradU x) - (y - h • V.gradU y)‖ ^ 2 ≤
      (1 - 2 * V.m * h + V.L ^ 2 * h ^ 2) * ‖x - y‖ ^ 2 := by
  have hidentity :
      ‖(x - h • V.gradU x) - (y - h • V.gradU y)‖ ^ 2 =
        ‖x - y‖ ^ 2 -
          2 * h * @inner ℝ (State d) _
            (V.gradU x - V.gradU y) (x - y) +
          h ^ 2 * ‖V.gradU x - V.gradU y‖ ^ 2 := by
    rw [show (x - h • V.gradU x) - (y - h • V.gradU y) =
        (x - y) - h • (V.gradU x - V.gradU y) by module]
    rw [norm_sub_sq_real, norm_smul, Real.norm_eq_abs,
      abs_of_nonneg hh, inner_smul_right, real_inner_comm]
    ring
  have hgrad := V.grad_lipschitz.norm_sub_le x y
  change ‖V.gradU x - V.gradU y‖ ≤ V.L * ‖x - y‖ at hgrad
  have hgradSq :
      ‖V.gradU x - V.gradU y‖ ^ 2 ≤ V.L ^ 2 * ‖x - y‖ ^ 2 := by
    have := (sq_le_sq₀ (norm_nonneg _)
      (mul_nonneg V.hL.le (norm_nonneg _))).2 hgrad
    simpa [mul_pow] using this
  have hcross := mul_le_mul_of_nonpos_left (V.gradU_strongMonotone x y)
    (by nlinarith : -2 * h ≤ 0)
  have hnoise := mul_le_mul_of_nonneg_left hgradSq (sq_nonneg h)
  rw [hidentity]
  calc
    ‖x - y‖ ^ 2 -
          2 * h * @inner ℝ (State d) _
            (V.gradU x - V.gradU y) (x - y) +
          h ^ 2 * ‖V.gradU x - V.gradU y‖ ^ 2
        ≤ ‖x - y‖ ^ 2 +
            (-2 * h) * (V.m * ‖x - y‖ ^ 2) +
            h ^ 2 * (V.L ^ 2 * ‖x - y‖ ^ 2) := by
          linarith
    _ = (1 - 2 * V.m * h + V.L ^ 2 * h ^ 2) * ‖x - y‖ ^ 2 := by ring

/-- Norm form of `eulerDrift_sq_le`, with the nonnegative square root of the
exact contraction factor. -/
lemma eulerDrift_norm_le (h : ℝ) (hh : 0 ≤ h) (x y : State d) :
    ‖(x - h • V.gradU x) - (y - h • V.gradU y)‖ ≤
      V.eulerContractionFactor h * ‖x - y‖ := by
  apply (sq_le_sq₀ (norm_nonneg _)
    (mul_nonneg (V.eulerContractionFactor_nonneg h) (norm_nonneg _))).mp
  have hsquare := V.eulerDrift_sq_le h hh x y
  rw [mul_pow, V.eulerContractionFactor_sq]
  exact hsquare

end FirstOrderPotential
end Concrete
end
end UniformRandomMALA
